# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='用户830644', max_length=20, verbose_name='nickname'),
        ),
    ]
