# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180423_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='用户910744', max_length=20, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='school_id',
            field=models.IntegerField(null=True, verbose_name='school_id'),
        ),
    ]
