# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180423_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='用户607255', max_length=20, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='school_id',
            field=models.CharField(max_length=13, null=True, unique=True, verbose_name='school_id'),
        ),
    ]
