# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180423_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='用户200242', max_length=20, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='sex',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], default=1, max_length=2),
        ),
    ]
