# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180423_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer811335', max_length=20, verbose_name='nickname'),
        ),
    ]
