# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 21:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180423_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='blacklist',
            field=models.ManyToManyField(blank=True, null=True, related_name='_loginuser_blacklist_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_loginuser_friends_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer775248', max_length=20, verbose_name='nickname'),
        ),
    ]
