# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180423_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='blacklist',
            field=models.ManyToManyField(blank=True, related_name='_loginuser_blacklist_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_loginuser_friends_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer315915', max_length=20, verbose_name='nickname'),
        ),
    ]
