# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20180425_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='fans',
            field=models.ManyToManyField(blank=True, related_name='_loginuser_fans_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer875945', max_length=20, verbose_name='nickname'),
        ),
    ]
