# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 20:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180425_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='blacklist',
        ),
        migrations.AddField(
            model_name='loginuser',
            name='blacklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shields', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='fans',
        ),
        migrations.AddField(
            model_name='loginuser',
            name='fans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='friends',
        ),
        migrations.AddField(
            model_name='loginuser',
            name='friends',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer910435', max_length=20, verbose_name='nickname'),
        ),
    ]
