# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180425_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='blacklist',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='fans',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='friends',
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer915816', max_length=20, verbose_name='nickname'),
        ),
        migrations.AddField(
            model_name='follow',
            name='blacklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shields', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='fans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
