# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20180425_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='blacklist',
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer126256', max_length=20, verbose_name='nickname'),
        ),
    ]
