# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20180425_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer466970', max_length=20, verbose_name='nickname'),
        ),
    ]
