# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20180426_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer855579', max_length=20, verbose_name='nickname'),
        ),
    ]
