# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20180427_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer639963', max_length=20, verbose_name='nickname'),
        ),
    ]
