# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20180507_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer517407', max_length=20, verbose_name='nickname'),
        ),
    ]
