# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20180509_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer65298', max_length=20, verbose_name='nickname'),
        ),
    ]
