# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 22:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20180509_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follow',
            new_name='follows',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='fans',
        ),
        migrations.AddField(
            model_name='follow',
            name='owner',
            field=models.ForeignKey(default=2016301500226, on_delete=django.db.models.deletion.CASCADE, related_name='follows_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer228856', max_length=20, verbose_name='nickname'),
        ),
        migrations.AddField(
            model_name='fans',
            name='fans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fans',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
