# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20180511_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer680754', max_length=20, verbose_name='nickname'),
        ),
        migrations.AlterModelTable(
            name='fans',
            table='Fans',
        ),
    ]
