# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_auto_20180521_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer18007', max_length=20, verbose_name='nickname'),
        ),
    ]
