# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 15:46
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_auto_20180521_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='headimg',
            field=models.ImageField(default='user/moren.jpeg', upload_to=account.models.get_upload_to, verbose_name='headimg'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer71741', max_length=20, verbose_name='nickname'),
        ),
    ]
