# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_auto_20180521_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer315782', max_length=20, verbose_name='nickname'),
        ),
    ]
