# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_auto_20180521_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer153036', max_length=20, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='school_id',
            field=models.CharField(default='', max_length=13, unique=True, verbose_name='school_id'),
        ),
    ]
