# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_auto_20180522_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer327736', max_length=20, verbose_name='nickname'),
        ),
    ]
