# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_auto_20180601_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer871545', max_length=20, verbose_name='nickname'),
        ),
    ]
