# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20180707_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer651693', max_length=20, verbose_name='nickname'),
        ),
    ]
