# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_auto_20180708_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer904382', max_length=20, verbose_name='nickname'),
        ),
    ]
