# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_auto_20180719_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer431277', max_length=20, verbose_name='nickname'),
        ),
    ]
