# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_auto_20180907_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer810534', max_length=20, verbose_name='nickname'),
        ),
    ]
