# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_auto_20180907_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer953097', max_length=20, verbose_name='nickname'),
        ),
    ]
