# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0058_auto_20180910_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer953500', max_length=20, verbose_name='nickname'),
        ),
    ]
