# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_auto_20181017_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer203760', max_length=20, verbose_name='nickname'),
        ),
    ]
