# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0065_auto_20181018_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer293406', max_length=20, verbose_name='nickname'),
        ),
    ]
