# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0066_auto_20181018_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='nickname',
            field=models.CharField(default='WHUer271083', max_length=20, verbose_name='nickname'),
        ),
    ]
