# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0002_postcomment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='updated_at',
        ),
    ]
