# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circle', '0003_remove_postcomment_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=144, verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commentParent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='circle.PostComment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentReply', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
