# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circle', '0004_postcommentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcommentreply',
            name='toWho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replyTome', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcommentreply',
            name='commentParent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='circle.PostComment'),
        ),
    ]
