# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0005_auto_20180910_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='passage',
        ),
        migrations.AddField(
            model_name='pypost',
            name='images',
            field=models.CharField(default='', max_length=1024, verbose_name='images'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
