# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 18:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='book_name')),
                ('language', models.CharField(choices=[('ch', '中文'), ('en', '英文')], default='ch', max_length=2, verbose_name='language')),
                ('country', models.CharField(choices=[('in', '国内'), ('out', '国外')], default='in', max_length=3, verbose_name='country')),
                ('types', models.CharField(choices=[('1', '教辅'), ('2', '课外')], default='2', max_length=1, verbose_name='types')),
                ('place', models.CharField(choices=[('1', '信息学部'), ('2', '文理学部'), ('3', '工学部'), ('4', '医学部')], default='1', max_length=1, verbose_name='place')),
                ('level', models.IntegerField(default=1, verbose_name='level')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Book',
                'ordering': ['level'],
            },
        ),
    ]
