# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 19:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainpage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('image', models.ImageField(null=True, upload_to=mainpage.models.get_book_upload_to, verbose_name='image')),
                ('language', models.CharField(choices=[('ch', '中文'), ('en', '英文')], default='ch', max_length=2, verbose_name='language')),
                ('country', models.CharField(choices=[('in', '国内'), ('out', '国外')], default='in', max_length=3, verbose_name='country')),
                ('types', models.CharField(choices=[('1', '教辅'), ('2', '课外')], default='2', max_length=1, verbose_name='types')),
                ('place', models.CharField(choices=[('1', '信息学部'), ('2', '文理学部'), ('3', '工学部'), ('4', '医学部')], default='1', max_length=1, verbose_name='place')),
                ('level', models.CharField(max_length=4, verbose_name='level')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Book',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='shop_name')),
                ('location', models.CharField(default='1', max_length=1, verbose_name='location')),
                ('image', models.ImageField(default='moren.jpg', upload_to=mainpage.models.get_food_upload_to, verbose_name='images')),
                ('rating', models.FloatField(default=0.0, verbose_name='rating')),
                ('introduce', models.CharField(max_length=64, null=True, verbose_name='introduce')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Shop',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=140, verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Food', to='mainpage.Food')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FoodComment',
                'ordering': ['created_at'],
            },
        ),
    ]
