# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainpage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('1', '信息学部'), ('2', '文理学部'), ('3', '工学部'), ('4', '医学部')], default='1', max_length=1, verbose_name='location')),
                ('title', models.CharField(max_length=16, verbose_name='title')),
                ('content', models.CharField(max_length=114, verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animalsAuthor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalSaveMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('1', '信息学部'), ('2', '文理学部'), ('3', '工学部'), ('4', '医学部')], default='1', max_length=1, verbose_name='location')),
                ('tel', models.CharField(max_length=149, verbose_name='telephone')),
                ('groupChat', models.CharField(max_length=149, verbose_name='groupChat')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '未查看'), (1, '已同意'), (2, '未同意')], default=0, verbose_name='status')),
            ],
            options={
                'verbose_name_plural': '图书交换申请',
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('images', models.CharField(default='', max_length=1024, verbose_name='image')),
                ('language', models.CharField(choices=[('ch', '中文'), ('en', '英文')], default='ch', max_length=2, verbose_name='language')),
                ('country', models.CharField(choices=[('in', '国内'), ('out', '国外')], default='in', max_length=3, verbose_name='country')),
                ('types', models.CharField(choices=[('1', '教辅'), ('2', '课外')], default='2', max_length=1, verbose_name='types')),
                ('place', models.CharField(choices=[('1', '信息学部'), ('2', '文理学部'), ('3', '工学部'), ('4', '医学部')], default='1', max_length=1, verbose_name='place')),
                ('level', models.CharField(max_length=4, verbose_name='level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Book',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='shop_name')),
                ('location', models.CharField(choices=[('1', '信息学部'), ('2', '文理学部'), ('3', '工学部'), ('4', '医学部'), ('5', '校外商家'), ('6', '校内商家')], default='1', max_length=1, verbose_name='location')),
                ('images', models.CharField(default='', max_length=1024, verbose_name='image')),
                ('rating', models.FloatField(default=0.0, verbose_name='rating')),
                ('introduce', models.CharField(max_length=64, null=True, verbose_name='introduce')),
                ('number', models.IntegerField(default=0, verbose_name='number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Shop',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=140, verbose_name='content')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mainpage.Food')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FoodComment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=mainpage.models.get_image_upload_to, verbose_name='images')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='frombook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frombook', to='mainpage.Book'),
        ),
        migrations.AddField(
            model_name='application',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appli_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appli_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='tobook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tobook', to='mainpage.Book'),
        ),
    ]
