# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='images',
            field=models.CharField(default='http://p9260z3xy.bkt.clouddn.com/books/mask.png', max_length=1024, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='food',
            name='images',
            field=models.CharField(default='http://p9260z3xy.bkt.clouddn.com/books/mask.png', max_length=1024, verbose_name='image'),
        ),
    ]
