# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcomment',
            name='score',
            field=models.IntegerField(default=0, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='food',
            name='location',
            field=models.CharField(choices=[('1', '信息学部'), ('2', '文理学部'), ('3', '工学部'), ('4', '医学部'), ('5', '校外商家'), ('6', '校内商家')], default='1', max_length=1, verbose_name='location'),
        ),
    ]
