# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import mainpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20180425_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to=mainpage.models.get_upload_to, verbose_name='book_image'),
        ),
    ]
