# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20181017_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='images',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024, verbose_name='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='images',
            field=models.CharField(default='http://p9260z3xy.bkt.clouddn.com/foods/mask.png', max_length=1024, verbose_name='image'),
        ),
    ]
