# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20180509_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='number',
            field=models.IntegerField(default=0, verbose_name='number'),
        ),
    ]
