# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 22:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_food_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcomment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
