# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import mainpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20180511_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=mainpage.models.get_book_upload_to, verbose_name='image'),
            preserve_default=False,
        ),
    ]
