# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import mainpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_auto_20180521_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='mask.png', upload_to=mainpage.models.get_book_upload_to, verbose_name='image'),
        ),
    ]
