# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import mainpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_auto_20180521_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('1', '信息学部'), ('2', '文理学部'), ('3', '工学部'), ('4', '医学部')], default='1', max_length=1, verbose_name='location')),
                ('title', models.CharField(max_length=16, verbose_name='title')),
                ('content', models.CharField(max_length=114, verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalSaveMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('1', '信息学部'), ('2', '文理学部'), ('3', '工学部'), ('4', '医学部')], default='1', max_length=1, verbose_name='location')),
                ('tel', models.CharField(max_length=149, verbose_name='telephone')),
                ('groupChat', models.CharField(max_length=149, verbose_name='groupChat')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('1', '图书'), ('2', '商店'), ('3', '动物信息')], default='1', max_length=1, verbose_name='types')),
                ('owner', models.IntegerField(default=1, verbose_name='ownerId')),
                ('image', models.ImageField(upload_to=mainpage.models.get_image_upload_to, verbose_name='images')),
            ],
        ),
    ]
