# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_auto_20180707_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
