# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0015_animals_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='images',
            name='animalOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnimalImages', to='mainpage.Animals'),
        ),
        migrations.AlterField(
            model_name='images',
            name='bookOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BookImages', to='mainpage.Book'),
        ),
        migrations.AlterField(
            model_name='images',
            name='shopOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ShopImages', to='mainpage.Food'),
        ),
    ]
